<?php
declare(strict_types=1);
require_once __DIR__ . '/app/bootstrap.php';
require_auth();
$launchAllowed=env_bool('ALLOW_LOCAL_KIOSK_LAUNCH',false) && current_user()['role']==='admin';
render_header('Kiosk Kehadiran Wajah','Kamera digunakan pada komputer kiosk, bukan pada pelayan web');
?>
<div class="content-stack"><section class="alert alert-info"><span>Untuk hosting awam, jalankan <code>face_recognition.py</code> pada komputer Windows/Linux yang mempunyai webcam. Setiap sync turut memvalidasi profil pending/tidak sah; hanya profil dengan sampel mencukupi dimasukkan dalam model pengecaman.</span></section><section class="grid grid-3"><article class="card"><span class="stat-icon">1</span><h2>Konfigurasi</h2><p>Tetapkan <code>APP_API_URL</code> kepada URL HTTPS <code>/api/kiosk.php</code> dan <code>KIOSK_API_KEY</code> yang sama seperti pelayan.</p></article><article class="card"><span class="stat-icon">2</span><h2>Pasang ejen</h2><p>Pasang Python 3.11 dan jalankan <code>pip install -r requirements.txt</code> pada komputer kiosk.</p></article><article class="card"><span class="stat-icon">3</span><h2>Imbas</h2><p>Jalankan <code>run_face.bat</code> atau <code>python face_recognition.py</code>. Kamera kekal aktif sehingga kekunci Q ditekan.</p></article></section><section class="card"><h2>Pilihan pelancar Windows tempatan</h2><p class="muted">Pelancar web dimatikan secara lalai kerana proses hosting biasanya tiada desktop atau webcam. Ia hanya sesuai apabila Apache dan kiosk berjalan pada komputer Windows interaktif yang sama.</p><?php if($launchAllowed): ?><form method="post" action="scan.php"><?= csrf_field() ?><button class="btn btn-warning" type="submit" data-confirm="Lancarkan ejen kiosk pada komputer pelayan tempatan ini?">Lancarkan kiosk tempatan</button></form><?php else: ?><span class="badge badge-muted">ALLOW_LOCAL_KIOSK_LAUNCH=false</span><?php endif; ?></section><section class="card"><h2>Semakan operasi</h2><ul><li>Gunakan HTTPS sah; HTTP hanya boleh dibenarkan secara eksplisit untuk pembangunan localhost.</li><li>Dataset disimpan dalam cache tempatan yang diabaikan Git dan imej asal kekal di storan peribadi.</li><li>Semak persetujuan penjaga dan dasar biometrik sebelum pendaftaran wajah.</li></ul><a class="btn btn-secondary" href="rekod_kehadiran.php">Lihat rekod kehadiran</a></section></div>
<?php render_footer(); ?>
