<?php
declare(strict_types=1);
require_once __DIR__ . '/app/bootstrap.php';
require_once __DIR__ . '/app/telegram_service.php';
require_auth();
$date=isset($_GET['date'])?require_valid_date($_GET['date']):date('Y-m-d');
$stmt=db()->prepare("SELECT COUNT(s.student_id) total,COALESCE(SUM(a.status='Hadir'),0) hadir,COALESCE(SUM(a.status='Tidak Hadir'),0) tidak_hadir FROM student s LEFT JOIN attendance a ON a.student_id=s.student_id AND a.date=?");$stmt->bind_param('s',$date);$stmt->execute();$stats=$stmt->get_result()->fetch_assoc()?:['total'=>0,'hadir'=>0,'tidak_hadir'=>0];$total=(int)$stats['total'];$hadir=(int)$stats['hadir'];$tidak=(int)$stats['tidak_hadir'];$belum=max(0,$total-$hadir-$tidak);$rate=$total>0?round(($hadir/$total)*100):0;
$recentStmt=db()->prepare("SELECT a.student_id,s.name,a.time,a.status,a.source FROM attendance a JOIN student s ON s.student_id=a.student_id WHERE a.date=? ORDER BY COALESCE(a.time,'00:00:00') DESC LIMIT 6");$recentStmt->bind_param('s',$date);$recentStmt->execute();$recent=$recentStmt->get_result()->fetch_all(MYSQLI_ASSOC);
$telegramStmt=db()->prepare("SELECT COUNT(*) total,COALESCE(SUM(n.id IS NULL OR n.status IN ('failed','cancelled')),0) eligible,COALESCE(SUM(n.status='pending'),0) queued,COALESCE(SUM(n.status='sent'),0) sent,COALESCE(SUM(n.status='failed'),0) failed,COALESCE(SUM(n.status='cancelled'),0) cancelled FROM attendance a JOIN student s ON s.student_id=a.student_id LEFT JOIN notification_log n ON n.student_id=s.student_id AND n.attendance_date=a.date AND n.notification_type='absence' WHERE a.date=? AND a.status='Tidak Hadir' AND s.telegram_chat_id IS NOT NULL AND s.telegram_chat_id<>''");$telegramStmt->bind_param('s',$date);$telegramStmt->execute();$telegram=$telegramStmt->get_result()->fetch_assoc()?:[];
render_header('Dashboard','Ringkasan kehadiran pada '.date('d/m/Y',strtotime($date)));
?>
<div class="content-stack"><section class="card no-print"><form class="toolbar" method="get" action="dashboard.php"><div class="field"><label for="date">Pilih tarikh</label><input class="input" type="date" id="date" name="date" value="<?= e($date) ?>" required></div><button class="btn btn-primary" type="submit">Papar ringkasan</button></form></section>
<section class="grid grid-4" aria-label="Statistik kehadiran"><article class="card stat-card"><span class="stat-icon">♙</span><div><strong><?= $total ?></strong><span>Jumlah murid</span></div></article><article class="card stat-card"><span class="stat-icon">✓</span><div><strong><?= $hadir ?></strong><span>Hadir</span></div></article><article class="card stat-card"><span class="stat-icon">×</span><div><strong><?= $tidak ?></strong><span>Tidak Hadir</span></div></article><article class="card stat-card"><span class="stat-icon">%</span><div><strong><?= $rate ?>%</strong><span>Kadar hadir · <?= $belum ?> belum ditanda</span></div></article></section>
<section class="grid grid-2"><article class="card"><h2>Tindakan pantas</h2><p class="muted">Pilih cara merekod atau menyemak kehadiran.</p><div class="button-row"><a class="btn btn-primary" href="ambil_kehadiran.php">Buka panduan kiosk</a><a class="btn btn-secondary" href="manual_kehadiran.php?date=<?= e($date) ?>">Kehadiran manual</a></div></article><article class="card"><h2>Notifikasi Telegram</h2><p class="muted">Dashboard hanya menggilirkan kerja; tiada rangkaian Telegram berlaku dalam permintaan ini. Layak digilir/cuba semula: <strong><?= (int)($telegram['eligible']??0) ?></strong> · Dalam giliran: <strong><?= (int)($telegram['queued']??0) ?></strong> · Dihantar: <strong><?= (int)($telegram['sent']??0) ?></strong> · Gagal: <strong><?= (int)($telegram['failed']??0) ?></strong> · Dibatalkan: <strong><?= (int)($telegram['cancelled']??0) ?></strong>.</p><form method="post" action="telegram.php"><?= csrf_field() ?><input type="hidden" name="date" value="<?= e($date) ?>"><button class="btn btn-warning" type="submit" data-confirm="Masukkan notifikasi baharu, gagal atau dibatalkan yang kini layak ke baris gilir?">Gilir / cuba semula maksimum <?= telegram_batch_size() ?></button></form></article></section>
<section class="card"><div class="toolbar"><div><h2>Rekod terkini</h2><p class="muted">Masa yang dipaparkan ialah masa kehadiran efektif, bukan masa pembetulan dibuat.</p></div><a class="btn btn-secondary" href="rekod_kehadiran.php?date=<?= e($date) ?>">Lihat semua</a></div><?php if(!$recent):render_empty('Belum ada rekod','Gunakan kiosk atau kehadiran manual.');else:?><div class="table-wrap"><table class="data-table responsive"><thead><tr><th>ID Murid</th><th>Nama</th><th>Masa efektif</th><th>Sumber</th><th>Status</th></tr></thead><tbody><?php foreach($recent as $row):?><tr><td data-label="ID Murid"><?= e($row['student_id']) ?></td><td data-label="Nama"><?= e($row['name']) ?></td><td data-label="Masa efektif"><?= e($row['time']?date('h:i A',strtotime($row['time'])):'—') ?></td><td data-label="Sumber"><?= e($row['source']==='kiosk'?'Kiosk wajah':'Manual') ?></td><td data-label="Status"><?= status_badge($row['status']) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></div>
<?php render_footer(); ?>
